
server:
    port: 9080
     # use-forward-headers: true deprecated
    forward-headers-strategy:   FRAMEWORK

management:
   context-path: /admin

spring:
  application:
    name: admin-server

  boot:
     admin:
        context-path: /admin

  security:
    user:
      name: ${ADMIN_USER}
      password: ${ADMIN_PASSWORD}


